export interface CityTravelData {
  airport: { name: string; iata: string };
  hotel: { name: string; stars: number; estPricePerNightSAR: number };
  estFlightPriceSAR: number;
}

export const CITY_DATA: Record<string, CityTravelData> = {
  "Rijeka":     { airport:{name:"Rijeka Airport",iata:"RJK"}, hotel:{name:"Hotel Jadran",stars:4,estPricePerNightSAR:420}, estFlightPriceSAR:1650 },
  "Gdansk":     { airport:{name:"Gdansk Lech Walesa Airport",iata:"GDN"}, hotel:{name:"Hotel Gdansk",stars:4,estPricePerNightSAR:480}, estFlightPriceSAR:1420 },
  "Vilnius":    { airport:{name:"Vilnius Airport",iata:"VNO"}, hotel:{name:"Grand Hotel Kempinski Vilnius",stars:5,estPricePerNightSAR:780}, estFlightPriceSAR:1380 },
  "Sintra":     { airport:{name:"Lisbon Humberto Delgado Airport",iata:"LIS"}, hotel:{name:"Tivoli Palacio de Seteais",stars:5,estPricePerNightSAR:1200}, estFlightPriceSAR:1750 },
  "Dubrovnik":  { airport:{name:"Dubrovnik Airport",iata:"DBV"}, hotel:{name:"Hotel Excelsior",stars:5,estPricePerNightSAR:1450}, estFlightPriceSAR:1680 },
  "York":       { airport:{name:"Leeds Bradford Airport",iata:"LBA"}, hotel:{name:"The Grand Hotel York",stars:5,estPricePerNightSAR:820}, estFlightPriceSAR:1550 },
  "Bratislava": { airport:{name:"Bratislava Airport",iata:"BTS"}, hotel:{name:"Falkensteiner Hotel Bratislava",stars:4,estPricePerNightSAR:560}, estFlightPriceSAR:1280 },
  "Keswick":    { airport:{name:"Newcastle Airport",iata:"NCL"}, hotel:{name:"The Keswick Country House Hotel",stars:4,estPricePerNightSAR:680}, estFlightPriceSAR:1540 },
  "Piran":      { airport:{name:"Ljubljana Joze Pucnik Airport",iata:"LJU"}, hotel:{name:"Hotel Piran",stars:4,estPricePerNightSAR:520}, estFlightPriceSAR:1390 },
  "Petra":      { airport:{name:"King Hussein International Airport",iata:"AQJ"}, hotel:{name:"Movenpick Resort Petra",stars:5,estPricePerNightSAR:980}, estFlightPriceSAR:680 },
  "Prague":     { airport:{name:"Vaclav Havel Airport Prague",iata:"PRG"}, hotel:{name:"Four Seasons Hotel Prague",stars:5,estPricePerNightSAR:1800}, estFlightPriceSAR:1300 },
  "Krakow":     { airport:{name:"John Paul II International Airport Krakow",iata:"KRK"}, hotel:{name:"Hotel Copernicus",stars:5,estPricePerNightSAR:760}, estFlightPriceSAR:1250 },
  "Tallinn":    { airport:{name:"Lennart Meri Tallinn Airport",iata:"TLL"}, hotel:{name:"Hotel Telegraaf",stars:5,estPricePerNightSAR:820}, estFlightPriceSAR:1480 },
  "Riga":       { airport:{name:"Riga International Airport",iata:"RIX"}, hotel:{name:"Grand Palace Hotel Riga",stars:5,estPricePerNightSAR:680}, estFlightPriceSAR:1420 },
  "Bruges":     { airport:{name:"Brussels Airport",iata:"BRU"}, hotel:{name:"Hotel Dukes Palace Bruges",stars:5,estPricePerNightSAR:1050}, estFlightPriceSAR:1480 },
  "Lisbon":     { airport:{name:"Lisbon Humberto Delgado Airport",iata:"LIS"}, hotel:{name:"Bairro Alto Hotel",stars:5,estPricePerNightSAR:1380}, estFlightPriceSAR:1750 },
  "Porto":      { airport:{name:"Francisco Sa Carneiro Airport",iata:"OPO"}, hotel:{name:"The Yeatman",stars:5,estPricePerNightSAR:1250}, estFlightPriceSAR:1720 },
  "Barcelona":  { airport:{name:"Barcelona El Prat Airport",iata:"BCN"}, hotel:{name:"Hotel Arts Barcelona",stars:5,estPricePerNightSAR:1900}, estFlightPriceSAR:1580 },
  "Paris":      { airport:{name:"Paris Charles de Gaulle Airport",iata:"CDG"}, hotel:{name:"Le Meurice",stars:5,estPricePerNightSAR:3500}, estFlightPriceSAR:1650 },
  "Rome":       { airport:{name:"Rome Fiumicino Airport",iata:"FCO"}, hotel:{name:"Hotel Eden Rome",stars:5,estPricePerNightSAR:2800}, estFlightPriceSAR:1480 },
  "Florence":   { airport:{name:"Florence Peretola Airport",iata:"FLR"}, hotel:{name:"Portrait Firenze",stars:5,estPricePerNightSAR:2200}, estFlightPriceSAR:1520 },
  "Venice":     { airport:{name:"Venice Marco Polo Airport",iata:"VCE"}, hotel:{name:"Cipriani Venice",stars:5,estPricePerNightSAR:4200}, estFlightPriceSAR:1460 },
  "Amsterdam":  { airport:{name:"Amsterdam Airport Schiphol",iata:"AMS"}, hotel:{name:"Hotel de l Europe",stars:5,estPricePerNightSAR:2100}, estFlightPriceSAR:1480 },
  "Vienna":     { airport:{name:"Vienna International Airport",iata:"VIE"}, hotel:{name:"Hotel Sacher Wien",stars:5,estPricePerNightSAR:2400}, estFlightPriceSAR:1320 },
  "London":     { airport:{name:"Heathrow Airport",iata:"LHR"}, hotel:{name:"The Langham London",stars:5,estPricePerNightSAR:3200}, estFlightPriceSAR:1580 },
  "Berlin":     { airport:{name:"Berlin Brandenburg Airport",iata:"BER"}, hotel:{name:"Hotel Adlon Kempinski",stars:5,estPricePerNightSAR:2600}, estFlightPriceSAR:1380 },
  "Copenhagen": { airport:{name:"Copenhagen Airport",iata:"CPH"}, hotel:{name:"Hotel d Angleterre",stars:5,estPricePerNightSAR:2800}, estFlightPriceSAR:1520 },
  "Stockholm":  { airport:{name:"Stockholm Arlanda Airport",iata:"ARN"}, hotel:{name:"Grand Hotel Stockholm",stars:5,estPricePerNightSAR:2500}, estFlightPriceSAR:1560 },
  "Helsinki":   { airport:{name:"Helsinki-Vantaa Airport",iata:"HEL"}, hotel:{name:"Hotel Kamp",stars:5,estPricePerNightSAR:2200}, estFlightPriceSAR:1620 },
  "Oslo":       { airport:{name:"Oslo Gardermoen Airport",iata:"OSL"}, hotel:{name:"The Thief",stars:5,estPricePerNightSAR:2400}, estFlightPriceSAR:1640 },
  "Reykjavik":  { airport:{name:"Keflavik International Airport",iata:"KEF"}, hotel:{name:"Hotel Borg",stars:4,estPricePerNightSAR:1800}, estFlightPriceSAR:2200 },
  "Athens":     { airport:{name:"Athens International Airport",iata:"ATH"}, hotel:{name:"Hotel Grande Bretagne",stars:5,estPricePerNightSAR:2100}, estFlightPriceSAR:1200 },
  "Istanbul":   { airport:{name:"Istanbul Airport",iata:"IST"}, hotel:{name:"Four Seasons Sultanahmet",stars:5,estPricePerNightSAR:2400}, estFlightPriceSAR:880 },
  "Dubai":      { airport:{name:"Dubai International Airport",iata:"DXB"}, hotel:{name:"Burj Al Arab Jumeirah",stars:5,estPricePerNightSAR:4800}, estFlightPriceSAR:280 },
  "Abu Dhabi":  { airport:{name:"Abu Dhabi International Airport",iata:"AUH"}, hotel:{name:"Emirates Palace Mandarin Oriental",stars:5,estPricePerNightSAR:3800}, estFlightPriceSAR:240 },
  "Doha":       { airport:{name:"Hamad International Airport",iata:"DOH"}, hotel:{name:"Marsa Malaz Kempinski",stars:5,estPricePerNightSAR:2800}, estFlightPriceSAR:320 },
  "Muscat":     { airport:{name:"Muscat International Airport",iata:"MCT"}, hotel:{name:"Al Bustan Palace Ritz-Carlton",stars:5,estPricePerNightSAR:2200}, estFlightPriceSAR:380 },
  "Marrakech":  { airport:{name:"Marrakech Menara Airport",iata:"RAK"}, hotel:{name:"La Mamounia",stars:5,estPricePerNightSAR:3200}, estFlightPriceSAR:1280 },
  "Tokyo":      { airport:{name:"Tokyo Narita International Airport",iata:"NRT"}, hotel:{name:"The Peninsula Tokyo",stars:5,estPricePerNightSAR:3600}, estFlightPriceSAR:2800 },
  "Singapore":  { airport:{name:"Changi Airport",iata:"SIN"}, hotel:{name:"Marina Bay Sands",stars:5,estPricePerNightSAR:2200}, estFlightPriceSAR:1800 },
  "Bali":       { airport:{name:"Ngurah Rai International Airport",iata:"DPS"}, hotel:{name:"Four Seasons Resort Bali at Sayan",stars:5,estPricePerNightSAR:3000}, estFlightPriceSAR:2200 },
  "Phuket":     { airport:{name:"Phuket International Airport",iata:"HKT"}, hotel:{name:"Amanpuri",stars:5,estPricePerNightSAR:4500}, estFlightPriceSAR:1800 },
  "Cairo":      { airport:{name:"Cairo International Airport",iata:"CAI"}, hotel:{name:"Four Seasons Hotel Cairo at Nile Plaza",stars:5,estPricePerNightSAR:1800}, estFlightPriceSAR:680 },
  "Amman":      { airport:{name:"Queen Alia International Airport",iata:"AMM"}, hotel:{name:"Four Seasons Hotel Amman",stars:5,estPricePerNightSAR:1600}, estFlightPriceSAR:520 },
  "Tbilisi":    { airport:{name:"Tbilisi International Airport",iata:"TBS"}, hotel:{name:"Rooms Hotel Tbilisi",stars:5,estPricePerNightSAR:980}, estFlightPriceSAR:920 },
  "Cape Town":  { airport:{name:"Cape Town International Airport",iata:"CPT"}, hotel:{name:"The Silo Hotel",stars:5,estPricePerNightSAR:4200}, estFlightPriceSAR:2800 },
  "Sydney":     { airport:{name:"Sydney Kingsford Smith Airport",iata:"SYD"}, hotel:{name:"Park Hyatt Sydney",stars:5,estPricePerNightSAR:3800}, estFlightPriceSAR:3200 },
  "New York":   { airport:{name:"John F Kennedy International Airport",iata:"JFK"}, hotel:{name:"The Plaza Hotel",stars:5,estPricePerNightSAR:4200}, estFlightPriceSAR:2800 },
  "Santorini":  { airport:{name:"Santorini National Airport",iata:"JTR"}, hotel:{name:"Canaves Oia Suites",stars:5,estPricePerNightSAR:2800}, estFlightPriceSAR:1250 },
  "Salzburg":   { airport:{name:"Salzburg Airport W. A. Mozart",iata:"SZG"}, hotel:{name:"Hotel Sacher Salzburg",stars:5,estPricePerNightSAR:1800}, estFlightPriceSAR:1380 },
  "Valletta":   { airport:{name:"Malta International Airport",iata:"MLA"}, hotel:{name:"The Phoenicia Malta",stars:5,estPricePerNightSAR:1600}, estFlightPriceSAR:1180 },
  "Sarajevo":   { airport:{name:"Sarajevo International Airport",iata:"SJJ"}, hotel:{name:"Hotel Europe Sarajevo",stars:5,estPricePerNightSAR:680}, estFlightPriceSAR:1150 },
  "Ohrid":      { airport:{name:"Ohrid St Paul the Apostle Airport",iata:"OHD"}, hotel:{name:"Hotel Tino",stars:4,estPricePerNightSAR:420}, estFlightPriceSAR:1200 },
  "Plovdiv":    { airport:{name:"Plovdiv International Airport",iata:"PDV"}, hotel:{name:"Boutique Hotel Hebros",stars:4,estPricePerNightSAR:480}, estFlightPriceSAR:1180 },
  "Innsbruck":  { airport:{name:"Innsbruck Airport",iata:"INN"}, hotel:{name:"Adlers Hotel",stars:4,estPricePerNightSAR:980}, estFlightPriceSAR:1380 },
  "Bergen":     { airport:{name:"Bergen Airport Flesland",iata:"BGO"}, hotel:{name:"Terminus Hotel Bergen",stars:4,estPricePerNightSAR:1200}, estFlightPriceSAR:1680 },
  "Wadi Rum":   { airport:{name:"King Hussein International Airport",iata:"AQJ"}, hotel:{name:"Wadi Rum Night Luxury Camp",stars:5,estPricePerNightSAR:1800}, estFlightPriceSAR:680 },
  "Luxor":      { airport:{name:"Luxor International Airport",iata:"LXR"}, hotel:{name:"Sofitel Winter Palace Luxor",stars:5,estPricePerNightSAR:1200}, estFlightPriceSAR:720 },
  "Fez":        { airport:{name:"Fes Saiss Airport",iata:"FEZ"}, hotel:{name:"Riad Fes",stars:5,estPricePerNightSAR:1400}, estFlightPriceSAR:1320 },
  "Split":      { airport:{name:"Split Airport",iata:"SPU"}, hotel:{name:"Hotel Vestibul Palace",stars:5,estPricePerNightSAR:1200}, estFlightPriceSAR:1580 },
  "Kotor":      { airport:{name:"Tivat Airport",iata:"TIV"}, hotel:{name:"Cattaro Hotel",stars:4,estPricePerNightSAR:780}, estFlightPriceSAR:1450 },
  "Hallstatt":  { airport:{name:"Salzburg Airport W. A. Mozart",iata:"SZG"}, hotel:{name:"Heritage Hotel Hallstatt",stars:4,estPricePerNightSAR:1100}, estFlightPriceSAR:1400 },
  "Chefchaouen":{ airport:{name:"Tangier Ibn Battouta Airport",iata:"TNG"}, hotel:{name:"Lina Ryad and Spa",stars:4,estPricePerNightSAR:820}, estFlightPriceSAR:1350 },
  "Riyadh":     { airport:{name:"King Khalid International Airport",iata:"RUH"}, hotel:{name:"Four Seasons Hotel Riyadh",stars:5,estPricePerNightSAR:2200}, estFlightPriceSAR:120 },
  "Jeddah":     { airport:{name:"King Abdulaziz International Airport",iata:"JED"}, hotel:{name:"Rosewood Jeddah",stars:5,estPricePerNightSAR:2400}, estFlightPriceSAR:180 },
};

export function getCityData(city: string): CityTravelData {
  return CITY_DATA[city] ?? {
    airport: { name: "International Airport", iata: "—" },
    hotel: { name: "Premier Hotel " + city, stars: 4, estPricePerNightSAR: 680 },
    estFlightPriceSAR: 1400,
  };
}